CREATE TABLE [dbo].[PosItem] (    
    [ItemId]           CHAR (6)        NOT NULL,
    [CustomCode]        VARCHAR (255)   NOT NULL,
    [Description]         VARCHAR (250)   NULL,
    [ShortDesc]         VARCHAR (50)    NULL,
    [GenericDesc]       VARCHAR (50)    NULL,
    [ClassID]           CHAR (3)        NULL,
    [ITEM_CATEGORY]     CHAR (3)        NULL,
    [PackCode]          CHAR (3)        NULL,
    [Manucode]          CHAR (6)        NULL,
    [ItemType]          INT             NULL,
    [ValuationMethod]   INT             NULL,
    [MCode]             CHAR (3)        NULL,
    [SaleTaxOption]     INT             NULL,
    [SaleTaxCode]       CHAR (3)        NULL,
    [PurchaseTaxOption] INT             NULL,
    [PurchaseTaxCode]   CHAR (3)        NULL,
    [SiteId]            CHAR (3)        NULL,
    [BinID]             CHAR (3)        NULL,
    [PurchaseCost]      NUMERIC (18, 4) NULL,
    [SalePrice]          NUMERIC (18, 4) NULL,
    [Sed]               NUMERIC (18)    NULL,
    [MaxSaleQty]        NUMERIC (18)    NULL,
    [Itype]             INT             NULL,
    [ReorderQty]        INT             NULL,
    [AvgRate]           NUMERIC (18, 3) NULL,
    [AvgRate1]          NUMERIC (18, 3) NULL,
    [SaleDiscPerc]      NUMERIC (18, 2) NULL,
    [PriceDescCStatus]  INT             NULL,
    [QtyCStatus]        INT             NULL,
    [DAvgRate]          NUMERIC (18, 3) NULL,
    [discper]           NUMERIC (18, 2) NULL,
    [discamt]           NUMERIC (18)    NULL,
    [StockS]            NUMERIC (18, 2) NULL,
    [StockG]            NUMERIC (18, 2) NULL,
    [packqty]           NUMERIC (18, 2) NULL,
    [packdisc]          NUMERIC (18, 2) NULL,
    [QtyAnAllow]        INT             NULL,
    [TmpFld1]           NCHAR (10)      NULL,
    [TmpFld2]           NCHAR (10)      NULL,
    [FxdPer]            NUMERIC (18, 2) NULL,
    [PCost]             NUMERIC (18, 4) NULL,
    [RoundCost]         NUMERIC (18, 2) NULL,
    [AddDateTime]       DATETIME        NULL,
    [EditDateTime]      DATETIME        NULL,
    [LastDiscAmt]       NUMERIC (18, 2) NULL,
    [STATUS]            NCHAR (10)      NULL,
    [REMARKS]           NCHAR (10)      NULL,
    [CreateUser]       NCHAR (10)      NOT NULL,
    [CreateDate]       DATETIME        NOT NULL,
    [UpdateUser]       NCHAR (10)      NULL,
    [UpdateDate]       DATETIME        NULL,
    [CompanyID]        CHAR (3)        NOT NULL,
    [SUB_COMPANY_ID]    NUMERIC (18)    NULL,
    [RT_ID]             NCHAR (3)       NULL,
    [type]              NCHAR (10)      NULL,
    [CatCode]           NCHAR (10)      NULL,
    [Branch_ID]         INT             NULL
);

