CREATE TABLE [dbo].[UserLog] (
    [UserLogID]             BIGINT             IDENTITY (1, 1) NOT NULL,
    [UserID]                BIGINT             NOT NULL,
    [AppID]                 BIGINT             NOT NULL,
    [DeviceTypeID]          BIGINT             NULL,
    [SessStart]             DATETIMEOFFSET (2) NULL,
    [SessEnd]               DATETIMEOFFSET (2) NULL,
    [MachineIP]             VARCHAR (20)       NULL,
    [CreateDate]            DATETIME           NULL,
    [Ip]                    VARCHAR (30)       NULL,
    [City]                  VARCHAR (20)       NULL,
    [Region]                VARCHAR (20)       NULL,
    [Region_code]           VARCHAR (20)       NULL,
    [Country]               VARCHAR (20)       NULL,
    [Country_name]          VARCHAR (20)       NULL,
    [Continent_code]        VARCHAR (20)       NULL,
    [In_eu]                 BIT                NULL,
    [Postal]                VARCHAR (20)       NULL,
    [Latitude]              DECIMAL (19, 10)   NULL,
    [Longitude]             DECIMAL (19, 10)   NULL,
    [TimeZone]              VARCHAR (20)       NULL,
    [Utc_offset]            VARCHAR (20)       NULL,
    [Country_calling_code]  VARCHAR (20)       NULL,
    [Currency]              VARCHAR (20)       NULL,
    [Languages]             VARCHAR (50)       NULL,
    [Asn]                   VARCHAR (20)       NULL,
    [Org]                   VARCHAR (50)       NULL,
    [IsAttemptSuccessful]   BIT                NULL,
    [AttemptDescription]    VARCHAR (MAX)      NULL,
    [IsAuthorisedCurrently] BIT                NULL,
    [IsCredentialValid]     BIT                NULL,
    [IsLoginSuccessful]     BIT                NULL,
    [IsEmailCorrect]        BIT                NULL,
    [IsPasswordExpired]     BIT                NULL,
    [LockoutEnabled]        BIT                NULL,
    [LockoutEnd]            DATETIMEOFFSET (7) NULL,
    [browser]               VARCHAR (MAX)      NULL,
    [os]                    VARCHAR (MAX)      NULL,
    [device]                VARCHAR (MAX)      NULL,
    [userAgent]             VARCHAR (MAX)      NULL,
    [os_version]            VARCHAR (MAX)      NULL,
    [isMobile]              BIT                NULL,
    [isTablet]              BIT                NULL,
    [isDesktop]             BIT                NULL,
    [RememberUser]          BIT                NULL,
    [SessionToken]          VARCHAR (MAX)      NULL,
    [TokenExpirationDate]   DATETIMEOFFSET (2) NULL
);

